name: iOS Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4 # تم التحديث للإصدار الرابع

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # تم التحديث للإصدار الرابع
        with:
          name: ios-build
          path: build/ios/iphoneos
